config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :events

  devise_for :members, controllers: {registration: "registration"}

  get 'dashboard/index'
  get 'dashboard/' => 'dashboard#index'
  get 'members/edit' => 'members#edit'

  get 'members' => 'dashboard#index'

  post 'events/:id/' => 'events#attend' , :as => :attend

  post 'dashboard/index' => 'dashboard#submit', :as => :submit



  get 'home/index'
  root 'home#index'

  get 'members/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
  put 'members/:id' => 'devise/registrations#update', :as => 'user_registration'





end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_member!

  def index
    @message = "Welcome to your dashboard!"
  end

  def edit
    @member = current_member
  end

  def submit

    #@member = Member.find(current_member.id)
    @member = current_member

    @work = params[:work]

    @member.work = @work

    @member.save!

    redirect_to root_path

  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<center>
  <%= image_tag("logo.jpg") %>
<h1>Member Dashboard</h1>
</center>
<p>

  <br>

  <center>

  Hi, <b> <%= current_member.firstname %> <%= current_member.middleinitial %> <%= current_member.lastname %> </b>
  <br>
  You have <b> <%= current_member.points %> </b> points.

  <div>
    Your email is <b> <%= current_member.email %> </b>
    <br>
    Your birthday is <b> <%= current_member.birthday %> </b>
    <br>
    You live in <b> <%= current_member.address %> </b>
  </div>

  <div>
    Your ID Number is <b> <%= current_member.idnumber %> </b>
    <br>
    You are <b> <%= current_member.year %> <%= current_member.course %> </b>

  </div>

  <br>
  <br>

  <div>

    <b>Emergency Details:</b>
    <br>
    <%= current_member.emergency_person %>
    <br>
    <%= current_member.emergency_phone %>

  </div>

  <br>

    <div>

        <%= form_for(:work, url: submit_path) do |f| %>

        <b>Upload Work</b> <br>
          <%= f.file_field :work %>
          <br>
          <%= f.submit 'Upload' %>
        <% end %>
    </div>

  <br>

  <div>
    <b>Uploaded Works:</b><br>
    <%= link_to current_member.work, current_member.work.url %>
    <br>

  </div>

  <br>


</center>

app/views/dashboard/work.html.erb
<%= form_for(current_member) do |f| %>
  <div class="field">
    <%= f.label :work %><br>
    <%= f.file_field :work %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= form_for(@member) do |f| %>
  <div class="field">
    <%= f.label :work %><br>
    <%= f.file_field :work %>
  </div>
  <div class="actions">
    <%= f.submit :Upload %>
  </div>