config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :events

  devise_for :members, controllers: {registration: "registration"}

  get 'dashboard/index'
  get 'dashboard/' => 'dashboard#index'
  get 'members/edit' => 'members#edit'

  get 'members' => 'dashboard#index'

  post 'events/:id/' => 'events#attend' , :as => :attend

  post 'dashboard/index' => 'dashboard#submit', :as => :submit



  get 'home/index'
  root 'home#index'

  get 'members/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
  put 'members/:id' => 'devise/registrations#update', :as => 'user_registration'





end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :members

  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end



  def attend

    @event = Event.find(params[:id])

     if member_signed_in?
       #before_action :authenticate_member!

       @event.attendance = @event.attendance + 1
       @event.save!

       current_member.points = current_member.points + @event.addpoint
       current_member.save!
       redirect_to event_path

     else

       @idnumber = params[:login_params][:idnumber]
       @email = params[:login_params][:email]


       @member = Member.where(:idnumber => @idnumber, :email => @email ).first


       if @member.nil?
         redirect_to event_path
         #show alert that member does not exist
       else
         @event.attendance = @event.attendance + 1
         @event.save!

         @member.points = @member.points + @event.addpoint
         @member.save!
         redirect_to event_path
       end

     end





  end

  def new
    @event = Event.new
  end

  def edit
  end


  def create

    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy

    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:eventid, :name, :organized_by, :venue, :schedule, :eventclass, :attendance, :addpoint)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :eventid %><br>
    <%= f.text_field :eventid %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :venue %><br>
    <%= f.text_area :venue %>
  </div>
  <div class="field">
    <%= f.label :organized_by %><br>
    <%= f.text_area :organized_by %>
  </div>

  <div class="field">
    <%= f.label :schedule %><br>
    <%= f.datetime_select :schedule %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :eventclass %>
  </div>
  <div class="field">
    <%= f.label :attendance %><br>
    <%= f.number_field :attendance %>
  </div>
  <div class="field">
    <%= f.label :addpoint %><br>
    <%= f.text_field :addpoint %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<center>
  <%= image_tag("logo.jpg") %>
<h1>Events</h1>
<center>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Venue</th>
      <th>Organized By</th>
      <th>Schedule</th>
      <th>Type</th>
      <th>Attendance</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.name, event %></td>
        <td><%= event.venue %></td>
        <td><%= event.organized_by %></td>
        <td><%= event.schedule.to_formatted_s(:long_ordinal)  %></td>
        <td><%= event.eventclass %></td>
        <td><%= event.attendance %></td>



      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<center>

<p>
  <h2>
  <b> <%= @event.name %> </b>  by <b> <%= @event.organized_by %> </b>
</h2>
  <br>

  <b> <%= @event.venue %></b> on </b><%= @event.schedule.strftime("%A %M /%D /%Y") %></b>

  <br>

  <b><%= @event.eventclass %></b>

  <br>

  Attendance: <b><%= @event.attendance %></b>

<br>
<br>
<br>
<br>
<br>
<br>
<br>


    <% if member_signed_in? %>
      <%=  button_to 'Register', :controller => "events", :action => "attend" %>
    <% else %>

      <%= form_for(:login_params, url: attend_path) do |f| %>
        <h3>ID Number</h3>
        <br>
        <%= f.text_field :idnumber %>
        <br>
        <h3>Email</h3>
        <br>
        <%= f.text_field :email %>
        <br>
        <br>
        <%= f.submit 'Register' %>

      <% end %>
    <% end %>

</p>

</center>