config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :events

  devise_for :members, controllers: {registration: "registration"}

  get 'dashboard/index'
  get 'dashboard/' => 'dashboard#index'
  get 'members/edit' => 'members#edit'

  get 'members' => 'dashboard#index'

  post 'events/:id/' => 'events#attend' , :as => :attend

  post 'dashboard/index' => 'dashboard#submit', :as => :submit



  get 'home/index'
  root 'home#index'

  get 'members/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
  put 'members/:id' => 'devise/registrations#update', :as => 'user_registration'





end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Writerskill</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <br>

<center>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</center>


  <div align = "right">

    <% if member_signed_in? %>

      <% if current_member_status == "Applicant" %>
        <%= link_to('Logout', destroy_member_session_path, :method => :delete) %>
      <% else %>
        <%= link_to('Dashboard', :controller => "dashboard", :action => "index") %>
        <%= link_to('Events', :controller => "events", :action => "index") %>
        <%= link_to('Logout', destroy_member_session_path, :method => :delete) %>
      <% end %>

    <% else %>

        <%= link_to('Home', root_path) %> |
        <%= link_to('Sign up', new_member_registration_path ) %> |
        <%= link_to('Login?', new_member_session_path)  %>

    <% end %>

    </div>




<%= yield %>

</body>


<footer>
  <br>
    <center>
    Writerskill Member System, All Rights Reserved.
  </center>

</footer>


</html>